# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"+\n\x15TelemetrySubscription\x12\x12\n\nsensor_ids\x18\x01 \x03(\t\"O\n\x10TelemetryMessage\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x19\n\x11timestamp_unix_ms\x18\x03 \x01(\x03\x32i\n\x10TelemetryService\x12U\n\x12SubscribeTelemetry\x12 .telemetry.TelemetrySubscription\x1a\x1b.telemetry.TelemetryMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYSUBSCRIPTION']._serialized_start=30
  _globals['_TELEMETRYSUBSCRIPTION']._serialized_end=73
  _globals['_TELEMETRYMESSAGE']._serialized_start=75
  _globals['_TELEMETRYMESSAGE']._serialized_end=154
  _globals['_TELEMETRYSERVICE']._serialized_start=156
  _globals['_TELEMETRYSERVICE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
