# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from device_controller.grpc_python import device_controller_pb2 as device__controller_dot_grpc__python_dot_device__controller__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_controller/grpc_python/device_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceManagerStub(object):
    """
    ============================
    DEVICE MANAGEMENT SERVICE
    ============================


    Handles registering, listing, or removing IoT devices.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDevice = channel.unary_unary(
                '/DeviceManager/RegisterDevice',
                request_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceInfo.SerializeToString,
                response_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/DeviceManager/ListDevices',
                request_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.Empty.SerializeToString,
                response_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceList.FromString,
                _registered_method=True)
        self.DeregisterDevice = channel.unary_unary(
                '/DeviceManager/DeregisterDevice',
                request_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceId.SerializeToString,
                response_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceResponse.FromString,
                _registered_method=True)


class DeviceManagerServicer(object):
    """
    ============================
    DEVICE MANAGEMENT SERVICE
    ============================


    Handles registering, listing, or removing IoT devices.
    """

    def RegisterDevice(self, request, context):
        """
        Registers a new IoT device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """
        Returns a list of all registered devices.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterDevice(self, request, context):
        """
        Deregisters an existing IoT device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceInfo.FromString,
                    response_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.Empty.FromString,
                    response_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceList.SerializeToString,
            ),
            'DeregisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterDevice,
                    request_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceId.FromString,
                    response_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeviceManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DeviceManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceManager(object):
    """
    ============================
    DEVICE MANAGEMENT SERVICE
    ============================


    Handles registering, listing, or removing IoT devices.
    """

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DeviceManager/RegisterDevice',
            device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceInfo.SerializeToString,
            device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DeviceManager/ListDevices',
            device__controller_dot_grpc__python_dot_device__controller__pb2.Empty.SerializeToString,
            device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DeviceManager/DeregisterDevice',
            device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceId.SerializeToString,
            device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceControlStub(object):
    """
    ============================
    DEVICE CONTROL SERVICE
    ============================


    Handles sending commands to IoT devices.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCommand = channel.unary_unary(
                '/DeviceControl/SendCommand',
                request_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.CommandRequest.SerializeToString,
                response_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamDeviceCommands = channel.unary_stream(
                '/DeviceControl/StreamDeviceCommands',
                request_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceId.SerializeToString,
                response_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.CommandResponse.FromString,
                _registered_method=True)


class DeviceControlServicer(object):
    """
    ============================
    DEVICE CONTROL SERVICE
    ============================


    Handles sending commands to IoT devices.
    """

    def SendCommand(self, request, context):
        """
        Sends a single command to a device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDeviceCommands(self, request, context):
        """
        Streams command responses for a device in real-time.
        Typical use: control panels subscribing to command execution updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.CommandRequest.FromString,
                    response_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.CommandResponse.SerializeToString,
            ),
            'StreamDeviceCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDeviceCommands,
                    request_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceId.FromString,
                    response_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeviceControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DeviceControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceControl(object):
    """
    ============================
    DEVICE CONTROL SERVICE
    ============================


    Handles sending commands to IoT devices.
    """

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DeviceControl/SendCommand',
            device__controller_dot_grpc__python_dot_device__controller__pb2.CommandRequest.SerializeToString,
            device__controller_dot_grpc__python_dot_device__controller__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDeviceCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/DeviceControl/StreamDeviceCommands',
            device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceId.SerializeToString,
            device__controller_dot_grpc__python_dot_device__controller__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceMonitorStub(object):
    """
    ============================
    DEVICE MONITORING SERVICE
    ============================


    Streams sensor data from IoT devices and allows clients to send configuration updates.
    Uses bidirectional streaming.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSensorData = channel.stream_stream(
                '/DeviceMonitor/StreamSensorData',
                request_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.SensorRequest.SerializeToString,
                response_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.SensorData.FromString,
                _registered_method=True)


class DeviceMonitorServicer(object):
    """
    ============================
    DEVICE MONITORING SERVICE
    ============================


    Streams sensor data from IoT devices and allows clients to send configuration updates.
    Uses bidirectional streaming.
    """

    def StreamSensorData(self, request_iterator, context):
        """
        Allows clients to send sensor subscription requests / config messages,
        and receive continuous sensor updates in return.

        - Client -> Server: sensor type preferences, sampling interval, etc.
        - Server -> Client: real-time sensor readings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSensorData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSensorData,
                    request_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.SensorRequest.FromString,
                    response_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.SensorData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeviceMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DeviceMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceMonitor(object):
    """
    ============================
    DEVICE MONITORING SERVICE
    ============================


    Streams sensor data from IoT devices and allows clients to send configuration updates.
    Uses bidirectional streaming.
    """

    @staticmethod
    def StreamSensorData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/DeviceMonitor/StreamSensorData',
            device__controller_dot_grpc__python_dot_device__controller__pb2.SensorRequest.SerializeToString,
            device__controller_dot_grpc__python_dot_device__controller__pb2.SensorData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AlertsStub(object):
    """
    ============================
    ALERTS / NOTIFICATIONS
    ============================


    Real-time alert subscription service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeAlerts = channel.unary_stream(
                '/Alerts/SubscribeAlerts',
                request_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceId.SerializeToString,
                response_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.Alert.FromString,
                _registered_method=True)


class AlertsServicer(object):
    """
    ============================
    ALERTS / NOTIFICATIONS
    ============================


    Real-time alert subscription service.
    """

    def SubscribeAlerts(self, request, context):
        """
        Streams alerts for a given device when thresholds or rules are triggered.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeAlerts,
                    request_deserializer=device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceId.FromString,
                    response_serializer=device__controller_dot_grpc__python_dot_device__controller__pb2.Alert.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Alerts', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Alerts', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Alerts(object):
    """
    ============================
    ALERTS / NOTIFICATIONS
    ============================


    Real-time alert subscription service.
    """

    @staticmethod
    def SubscribeAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Alerts/SubscribeAlerts',
            device__controller_dot_grpc__python_dot_device__controller__pb2.DeviceId.SerializeToString,
            device__controller_dot_grpc__python_dot_device__controller__pb2.Alert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
