# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\x12\x05\x61\x64min\"\x12\n\x10GetStatusRequest\"#\n\x11GetStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x10\n\x0eRestartRequest\"#\n\x0fRestartResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x32\x88\x01\n\x0c\x41\x64minService\x12>\n\tGetStatus\x12\x17.admin.GetStatusRequest\x1a\x18.admin.GetStatusResponse\x12\x38\n\x07Restart\x12\x15.admin.RestartRequest\x1a\x16.admin.RestartResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATUSREQUEST']._serialized_start=22
  _globals['_GETSTATUSREQUEST']._serialized_end=40
  _globals['_GETSTATUSRESPONSE']._serialized_start=42
  _globals['_GETSTATUSRESPONSE']._serialized_end=77
  _globals['_RESTARTREQUEST']._serialized_start=79
  _globals['_RESTARTREQUEST']._serialized_end=95
  _globals['_RESTARTRESPONSE']._serialized_start=97
  _globals['_RESTARTRESPONSE']._serialized_end=132
  _globals['_ADMINSERVICE']._serialized_start=135
  _globals['_ADMINSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
