# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import control_pb2 as control__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMotor = channel.unary_unary(
                '/control.ControlService/SetMotor',
                request_serializer=control__pb2.SetMotorRequest.SerializeToString,
                response_deserializer=control__pb2.SetMotorResponse.FromString,
                _registered_method=True)
        self.StopAll = channel.unary_unary(
                '/control.ControlService/StopAll',
                request_serializer=control__pb2.StopAllRequest.SerializeToString,
                response_deserializer=control__pb2.StopAllResponse.FromString,
                _registered_method=True)
        self.LiveControl = channel.stream_stream(
                '/control.ControlService/LiveControl',
                request_serializer=control__pb2.LiveControlRequest.SerializeToString,
                response_deserializer=control__pb2.LiveControlResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetMotor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveControl(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMotor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMotor,
                    request_deserializer=control__pb2.SetMotorRequest.FromString,
                    response_serializer=control__pb2.SetMotorResponse.SerializeToString,
            ),
            'StopAll': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAll,
                    request_deserializer=control__pb2.StopAllRequest.FromString,
                    response_serializer=control__pb2.StopAllResponse.SerializeToString,
            ),
            'LiveControl': grpc.stream_stream_rpc_method_handler(
                    servicer.LiveControl,
                    request_deserializer=control__pb2.LiveControlRequest.FromString,
                    response_serializer=control__pb2.LiveControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('control.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetMotor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.ControlService/SetMotor',
            control__pb2.SetMotorRequest.SerializeToString,
            control__pb2.SetMotorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.ControlService/StopAll',
            control__pb2.StopAllRequest.SerializeToString,
            control__pb2.StopAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiveControl(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/control.ControlService/LiveControl',
            control__pb2.LiveControlRequest.SerializeToString,
            control__pb2.LiveControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
