# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import robot_types_pb2 as common_dot_robot__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\x07\x63ontrol\x1a\x18\x63ommon/robot_types.proto\"8\n\x0fSetMotorRequest\x12%\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x14.common.MotorCommand\"$\n\x10SetMotorResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"\x10\n\x0eStopAllRequest\"\"\n\x0fStopAllResponse\x12\x0f\n\x07stopped\x18\x01 \x01(\x08\";\n\x12LiveControlRequest\x12%\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x14.common.MotorCommand\"8\n\x13LiveControlResponse\x12!\n\x05state\x18\x01 \x01(\x0b\x32\x12.common.RobotState2\xdd\x01\n\x0e\x43ontrolService\x12?\n\x08SetMotor\x12\x18.control.SetMotorRequest\x1a\x19.control.SetMotorResponse\x12<\n\x07StopAll\x12\x17.control.StopAllRequest\x1a\x18.control.StopAllResponse\x12L\n\x0bLiveControl\x12\x1b.control.LiveControlRequest\x1a\x1c.control.LiveControlResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETMOTORREQUEST']._serialized_start=52
  _globals['_SETMOTORREQUEST']._serialized_end=108
  _globals['_SETMOTORRESPONSE']._serialized_start=110
  _globals['_SETMOTORRESPONSE']._serialized_end=146
  _globals['_STOPALLREQUEST']._serialized_start=148
  _globals['_STOPALLREQUEST']._serialized_end=164
  _globals['_STOPALLRESPONSE']._serialized_start=166
  _globals['_STOPALLRESPONSE']._serialized_end=200
  _globals['_LIVECONTROLREQUEST']._serialized_start=202
  _globals['_LIVECONTROLREQUEST']._serialized_end=261
  _globals['_LIVECONTROLRESPONSE']._serialized_start=263
  _globals['_LIVECONTROLRESPONSE']._serialized_end=319
  _globals['_CONTROLSERVICE']._serialized_start=322
  _globals['_CONTROLSERVICE']._serialized_end=543
# @@protoc_insertion_point(module_scope)
